---
version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: .Dockerfile-compose
      args:
        CI_REPOSITORY: "${CI_REPOSITORY}"
        CI_REGISTRY_USER: "${CI_REGISTRY_USER}"
        CI_REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    env_file: .env
    container_name: "${CI_PROJECT_NAME}"
    hostname: "${K8S_APP_ING}"
    ports:
      - "${APP_LOCAL_PORT}:8080"
    networks:
      - bridge_mode
    shm_size: "256m"

networks:
  bridge_mode:
    driver: bridge
