INSERT INTO SCA.SECAO
(ID, SISTEMA, NOME, LINK, SECAOPAI, ORDEM, MENU, NIVEL)
VALUES((SELECT MAX(s.ID)+1 FROM sca.SECAO s), 7, 'ROLE_GTR', '-', 0, 0, 0, 0);

INSERT INTO SCA.SECAO
(ID, SISTEMA, NOME, LINK, SECAOPAI, ORDEM, MENU, NIVEL)
VALUES((SELECT MAX(s.ID)+1 FROM sca.SECAO s), 7, 'ROLE_GTR_ALTERAR', '-', 0, 0, 0, 0);

INSERT INTO SCA.SECAO
(ID, SISTEMA, NOME, LINK, SECAOPAI, ORDEM, MENU, NIVEL)
VALUES((SELECT MAX(s.ID)+1 FROM sca.SECAO s), 7, 'ROLE_GTR_EXCLUIR', '-', 0, 0, 0, 0);

INSERT INTO SCA.SECAO
(ID, SISTEMA, NOME, LINK, SECAOPAI, ORDEM, MENU, NIVEL)
VALUES((SELECT MAX(s.ID)+1 FROM sca.SECAO s), 7, 'ROLE_GTR_INSERIR', '-', 0, 0, 0, 0);

--------------------------------------------------------------------------------------------------------

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 25, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 25, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_INSERIR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 25, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_ALTERAR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 25, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_EXCLUIR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 34, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 34, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_INSERIR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 34, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_ALTERAR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 34, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_EXCLUIR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 47, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 47, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_INSERIR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 47, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_ALTERAR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 47, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR_EXCLUIR'));

INSERT INTO SCA.PERMISSAO
(ID, SISTEMA, GRUPO, SECAO)
VALUES((SELECT MAX(s.ID)+1 FROM sca.PERMISSAO s), 7, 48, (SELECT s2.ID  FROM SCA.SECAO s2 WHERE s2.NOME LIKE 'ROLE_GTR'));