CREATE TABLE FP_AUXILIOSAUDEREQDEP(
    ID NUMBER(10) CONSTRAINT NN_AUXILIOSAUDEREQDEP NOT NULL,
    IDAUXILIOSAUDEREQ NUMBER(6) CONSTRAINT NN_ID_AUXILIOSAUDEREQ NOT NULL,
    IDDEPENDENTE NUMBER(6) CONSTRAINT NN_ID_DEPENDENTE NOT NULL,
    IDPESSOAJURIDICA NUMBER(6),
    VALOR_PLANOSAUDE NUMBER(5,2),
    FLG_DELETADO CHAR(1),
    
    CONSTRAINT PK_AUXILIOSAUDEREQDEP PRIMARY KEY("ID"),

    CONSTRAINT "CK_FLG_DELETADO" CHECK (FLG_DELETADO IN (0,1)),
    
    CONSTRAINT FK_TBAUXILIOSAUDEREQ FOREIGN KEY (IDAUXILIOSAUDEREQ)
    REFERENCES FP_AUXILIOSAUDEREQ("ID"),
    
    CONSTRAINT FK_DEP_TBDEPENDENTE FOREIGN KEY (IDDEPENDENTE)
    REFERENCES TB_DEPENDENTE("ID"),
    
    CONSTRAINT "FK_DEP_TBPESSOAJURIDICA" FOREIGN KEY ("IDPESSOAJURIDICA")
    REFERENCES "SRH"."TB_PESSOAJURIDICA" ("ID")
)

CREATE SEQUENCE  "SRH"."SEQ_FP_AUXILIOSAUDEREQDEP"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;



CREATE TABLE FP_AUXILIOSAUDEDOC(
    ID NUMBER(10) CONSTRAINT NN_FP_AUXILIOSAUDEDOC NOT NULL,
    IDAUXILIOSAUDEREQ NUMBER(10),
    IDAUXILIOSAUDEREQDEP NUMBER(10),
    CAMINHO_ARQ VARCHAR(200),
    NOME_ARQ VARCHAR(200),
    DT_INCLUSAO DATE,
    FLG_DELETADO NUMBER(1) DEFAULT 0,
    
    CONSTRAINT "PK_AUXILIOSAUDEDOC" PRIMARY KEY ("ID"),
    
    CONSTRAINT "FK_DOC_AUXILIOSAUDEREQ" FOREIGN KEY ("IDAUXILIOSAUDEREQ")
    REFERENCES "SRH"."FP_AUXILIOSAUDEREQ" ("ID"),
    
    CONSTRAINT "FK_DOC_AUXILIOSAUDEREQDEP" FOREIGN KEY("IDAUXILIOSAUDEREQDEP")
    REFERENCES "SRH"."FP_AUXILIOSAUDEREQDEP" ("ID")
);

CREATE SEQUENCE  "SRH"."SEQ_FP_AUXILIOSAUDEDOC"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;